name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release archives
        run: |
          set -euo pipefail
          tag_name="${GITHUB_REF_NAME}"
          release_name="necesse-docker-server-${tag_name}"
          mkdir "${release_name}"
          cp Dockerfile docker-compose.yml entrypoint.sh README.md LICENSE .env.example CHANGELOG.md "${release_name}/"
          cp -r .github "${release_name}/.github"
          tar -czf "${release_name}.tar.gz" "${release_name}"
          zip -r "${release_name}.zip" "${release_name}"

      - name: Generate release notes
        run: |
          set -euo pipefail
          version="${GITHUB_REF_NAME#v}"
          awk -v ver="$version" '
            /^## \[/ {
              if (found) exit
              if ($0 ~ "^## \\[" ver "\\]") {found=1; next}
            }
            found {print}
          ' CHANGELOG.md | sed '/^$/d' > RELEASE_NOTES.md
          if [ ! -s RELEASE_NOTES.md ]; then
            echo "No changelog entry found for ${version}" >&2
            exit 1
          fi

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES.md
          files: |
            necesse-docker-server-${{ github.ref_name }}.tar.gz
            necesse-docker-server-${{ github.ref_name }}.zip

  docker-image:
    needs: package
    runs-on: ubuntu-latest
    if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute image metadata
        id: meta
        run: |
          version="${GITHUB_REF_NAME#v}"
          echo "version=$version" >>"$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            andreasgl4ser/necesse-server:${{ steps.meta.outputs.version }}
            andreasgl4ser/necesse-server:latest
          build-args: |
            BUILD_VERSION=${{ steps.meta.outputs.version }}
            BUILD_REVISION=${{ github.sha }}
